(() => {
"use strict";
const q=(s,r=document)=>r.querySelector(s),qa=(s,r=document)=>Array.from(r.querySelectorAll(s));
const esc=v=>String(v==null?"":v).replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[c]));
const money=v=>Number(v||0).toLocaleString("pt-BR",{style:"currency",currency:"BRL"});
const icon=(name)=>{const paths={truck:'<path d="M10 17h4V5H2v12h3"/><path d="M14 9h4l4 4v4h-3"/><circle cx="7.5" cy="17.5" r="2.5"/><circle cx="16.5" cy="17.5" r="2.5"/>',bike:'<circle cx="18.5" cy="17.5" r="3.5"/><circle cx="5.5" cy="17.5" r="3.5"/><path d="M15 6h4l-3 7H8l3-7h3"/><path d="m5.5 17.5 3-7.5H12"/>',package:'<path d="m16.5 9.4-9-5.2"/><path d="M21 16V8a2 2 0 0 0-1-1.73l-7-4a2 2 0 0 0-2 0l-7 4A2 2 0 0 0 3 8v8a2 2 0 0 0 1 1.73l7 4a2 2 0 0 0 2 0l7-4A2 2 0 0 0 21 16Z"/><path d="M3.3 7 12 12l8.7-5"/><path d="M12 22V12"/>',pin:'<path d="M20 10c0 5-8 12-8 12S4 15 4 10a8 8 0 1 1 16 0Z"/><circle cx="12" cy="10" r="3"/>',check:'<path d="M20 6 9 17l-5-5"/>'};return '<svg class="ui-icon" viewBox="0 0 24 24" aria-hidden="true" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">'+(paths[name]||paths.package)+'</svg>'};
let jobs=[],profiles=[],auth=null,progress=null,adminData=null,adminTab="profiles",lessonIndex=0,lessonReady=false;
const studyKey="puxarota-study-ripio-v2";
const studyState=JSON.parse(localStorage.getItem(studyKey)||'{"completed":[]}');
const lessons=[
{t:"Cartão pré-pago: o que é",d:"Saldo antes da compra, sem fatura nem parcelamento",body:"O cartão usa o saldo disponível na sua conta. Antes de comprar, confira se há valor suficiente e qual moeda está selecionada",img:"rupi-mascot.png",q:"O que acontece se não houver saldo suficiente?",o:["A compra pode ser recusada","O valor vira uma fatura","A compra é parcelada"],a:0},
{t:"Cripto e USDT na prática",d:"Entenda a moeda selecionada e a conversão no pagamento",body:"Você pode manter diferentes ativos na conta. A moeda escolhida como origem do pagamento é convertida quando necessário",img:"carcara-scout.png",q:"Qual cuidado vem antes de pagar?",o:["Conferir saldo e moeda selecionada","Comprar mais do que precisa","Ignorar a cotação"],a:0},
{t:"Parceiros e como usar o cashback",d:"Aprenda a localizar e ler uma oferta dentro do app",body:"As ofertas podem variar por região, perfil e nível. Abra o benefício na Ripio e leia o canal, o dia, o teto e a validade",img:"faro.png",q:"O que confirma uma oferta válida para você?",o:["O tile exibido na sua conta","Um comentário antigo","Um anúncio de outro país"],a:0},
{t:"Cashback pagando com cripto",d:"Compare retorno, regras e custos da operação",body:"A regra pública brasileira informa cashback-base maior ao pagar com ativo digital. Compare o retorno com cotação e comissão antes de decidir",img:"rupi-badge.png",q:"Qual é a comparação correta?",o:["Cashback líquido contra custos da operação","Somente o percentual maior","Somente o preço do produto"],a:0},
{t:"Baixe o aplicativo oficial",d:"Evite APKs e links recebidos de desconhecidos",body:"Use a loja oficial do seu aparelho e confira o desenvolvedor. Nunca instale arquivos enviados por mensagens",img:"carcara-flight.png",q:"Qual fonte é mais segura?",o:["A loja oficial do aparelho","Um APK recebido no grupo","Um link encurtado desconhecido"],a:0},
{t:"Cadastro pelo link",d:"Proteja a conta com senha exclusiva e biometria",body:"Crie uma senha exclusiva, ative a biometria quando disponível e nunca compartilhe códigos de acesso",img:"faro.png",q:"O que você nunca deve compartilhar?",o:["Código de acesso","Seu primeiro nome","A cidade onde trabalha"],a:0},
{t:"Pagando e acompanhando",d:"Guarde o comprovante e confira o crédito no app",body:"Depois da compra confirmada, acompanhe a transação. Em caso de diferença, o comprovante ajuda no atendimento",img:"rupi-next.png",q:"Por que guardar o comprovante?",o:["Para conferir e acionar o suporte","Para aumentar o nível sozinho","Para mudar a moeda depois"],a:0},
{t:"Descubra seu nível e seus parceiros",d:"Veja quais ofertas aparecem para seu perfil e região",body:"Abra a área de benefícios da Ripio e compare o que aparece na sua conta. Percentuais e limites podem ser personalizados",img:"carcara-scout.png",q:"As ofertas são sempre iguais para todos?",o:["Não, podem variar por perfil e região","Sim, são iguais no mundo todo","Sim, nunca mudam"],a:0},
{t:"NFC ou cartão físico",d:"Configure a carteira do celular ou ative o cartão físico",body:"No celular, adicione o cartão à carteira compatível e use a aproximação. No físico, confira a ativação antes da primeira compra",img:"rupi-mascot.png",q:"O que os dois formatos têm em comum?",o:["Usam o saldo da conta","Criam uma fatura mensal","Funcionam sem saldo"],a:0},
{t:"Escolha a moeda de pagamento",d:"Deixe saldo e selecione cripto ou reais antes da compra",body:"Antes de aproximar o celular ou passar o cartão, confirme a origem do pagamento no app",img:"rupi-hint.png",q:"Quando conferir a moeda selecionada?",o:["Antes da compra","Somente uma semana depois","Nunca é necessário"],a:0},
{t:"Escolha a cripto do cashback",d:"Confira as opções no app; BTC e USDT são os destaques",body:"As opções disponíveis aparecem na sua conta. BTC e USDT são escolhas comuns, mas têm comportamentos diferentes e nenhuma recompensa deve ser tratada como ganho garantido",img:"carcara-flight.png",q:"Onde ver as opções realmente disponíveis?",o:["Na sua conta Ripio","Em uma lista antiga","No app de outra pessoa"],a:0},
{t:"Leve o saldo até o pagamento",d:"Atividade de toque e arraste para praticar o preparo",body:"Escolha o saldo, confira o valor e leve a moeda até a carteira NFC",img:"rupi-mascot.png",game:true},
{t:"Checklist para garantir o cashback",d:"Confirme dia, canal, moeda, teto e prazo antes de pagar",body:"Uma oferta só deve orientar sua decisão depois que todos os campos importantes forem conferidos",img:"faro.png",q:"Qual item pode impedir o benefício?",o:["Usar um canal diferente do indicado","Guardar o comprovante","Conferir o teto"],a:0},
{t:"Simule antes de usar",d:"Calcule o retorno sem criar um gasto desnecessário",body:"A economia só existe quando a compra já fazia parte do seu plano. Use o simulador e compare o valor que volta com os custos",img:"rupi-badge.png",q:"Qual gasto faz sentido?",o:["O que já estava planejado","Um gasto criado apenas pelo cashback","Qualquer compra por impulso"],a:0},
{t:"Quando o cashback não entra",d:"Revise elegibilidade, cancelamentos e como pedir suporte",body:"Confira se a compra foi confirmada, se o canal era elegível e se o prazo terminou. Depois, use o comprovante ao falar com o suporte",img:"carcara-scout.png",q:"Qual é o primeiro passo?",o:["Revisar regra, status e prazo","Fazer outra compra","Apagar o comprovante"],a:0},
{t:"Sua economia do mês",d:"Registre quanto voltou e quais despesas valeram a pena",body:"Some apenas valores creditados e compare com seus gastos planejados. Esse histórico ajuda a escolher melhor no próximo mês",img:"rupi-next.png",q:"O que entra no resumo?",o:["Valores realmente creditados","Promessas futuras","Compras canceladas"],a:0}
];
function go(view){if(view==="admin"&&!isAdmin())view="perfil";qa("[data-view]").forEach(p=>{const on=p.dataset.view===view;p.hidden=!on;p.classList.toggle("active",on)});qa("[data-nav]").forEach(b=>b.classList.toggle("active",b.dataset.nav===view));history.replaceState(null,"","#"+view);window.scrollTo({top:0,behavior:"smooth"})}
function tags(values){return values.flat().filter(Boolean).map(x=>"<span>"+esc(x)+"</span>").join("")}
function first(v,fallback){return Array.isArray(v)?v[0]||fallback:v||fallback}
function vehicleIcon(value){return icon(String(value||"").toLowerCase().includes("moto")?"bike":"truck")}
function cargoType(job){return first(job.cargo_type||job.cargo||job.category,job.title||"Carga geral")}
function jobFacts(job){const vehicle=first(job.vehicles,"A combinar"),cargo=cargoType(job),place=job.origin||job.area||"A confirmar";return '<div class="job-visual"><div class="job-fact"><span>'+vehicleIcon(vehicle)+'</span><div><small>Veículo</small><b>'+esc(vehicle)+'</b></div></div><div class="job-fact"><span>'+icon("package")+'</span><div><small>Tipo de carga</small><b>'+esc(cargo)+'</b></div></div><div class="job-fact"><span>'+icon("pin")+'</span><div><small>Região</small><b>'+esc(place)+'</b></div></div></div>'}
function renderJobs(){const term=q("#job-search").value.trim().toLocaleLowerCase("pt-BR"),filtered=jobs.filter(j=>JSON.stringify(j).toLocaleLowerCase("pt-BR").includes(term));q("#jobs-status").textContent=filtered.length+" oportunidade"+(filtered.length===1?"":"s")+" encontrada"+(filtered.length===1?"":"s");q("#job-list").innerHTML=filtered.length?filtered.map((job,i)=>'<article class="job-card"><div class="job-head"><div><span class="eyebrow">'+esc(job.company||"EMPRESA")+'</span><h2>'+esc(job.title||"Oportunidade")+'</h2></div><span class="verified">&#10003; Verificada</span></div>'+jobFacts(job)+'<div class="tags">'+tags([job.model,job.routine,job.payment].concat(job.vehicles||[]))+'</div><div class="job-actions"><button class="ghost" data-job-detail="'+i+'" aria-expanded="false">Ver detalhes</button>'+(job.url?'<a href="'+esc(job.url)+'" target="_blank" rel="noopener nofollow">Fonte oficial &#8599;</a>':"")+'</div><div class="job-details" id="job-detail-'+i+'" hidden><p>'+esc(job.detail||"Consulte as condições completas antes de demonstrar interesse")+'</p><div class="detail-grid"><div><small>Origem</small><b>'+esc(job.origin||"A confirmar")+'</b></div><div><small>Atuação</small><b>'+esc(job.area||"A confirmar")+'</b></div><div><small>Modelo</small><b>'+esc(job.model||"A combinar")+'</b></div><div><small>Pagamento</small><b>'+esc(job.payment||"Consulte a fonte")+'</b></div></div></div></article>').join(""):'<article class="job-card"><h2>Nenhuma oportunidade com esse filtro</h2><p>Tente outra região, empresa ou veículo</p></article>'}
function renderProfiles(){q("#profiles-status").textContent=profiles.length+" perfil"+(profiles.length===1?"":"is")+" publicado"+(profiles.length===1?"":"s")+" com consentimento";q("#profile-list").innerHTML=profiles.length?profiles.map(p=>'<article class="profile-card"><span class="avatar">'+esc((p.display_name||"P").trim().charAt(0).toUpperCase())+'</span><div><span class="eyebrow">'+(p.profile_type==="helper"?"AJUDANTE":"MOTORISTA")+'</span><h2>'+esc(p.display_name||"Profissional")+'</h2><div class="tags">'+tags([p.region,p.vehicle,p.license_category,p.cargo_preference,p.availability])+'</div></div></article>').join(""):'<article class="profile-card"><span class="avatar">R</span><div><h2>A rede está começando</h2><p>Os perfis autorizados aparecem aqui</p></div></article>'}
function renderLessons(){q("#lessons").innerHTML=lessons.map((x,i)=>'<button class="lesson" data-lesson="'+i+'"><div><h3>'+esc(x.t)+'</h3><p>'+esc(x.d)+'</p></div><span class="'+(studyState.completed.includes(i)?"done":i<7?"old":"new")+'">'+(studyState.completed.includes(i)?"concluída":i<7?"preservada":"nova")+'</span></button>').join("")}
function renderProgress(){const state=progress||{},xp=Number(state.xp||0),ripio=state.routes&&state.routes["beneficios-ripio"]||{},step=Math.min(Number(ripio.step||0),7);q("#xp-count").textContent=auth?xp+" XP":"-";q("#xp-note").textContent=auth?Number(state.streak||0)+" dia(s) de sequência":"entre para sincronizar";q("#ripio-progress").textContent=auth?"progresso existente: "+step+"/7":"entre para ver o progresso";q("#lesson-note").textContent=auth?step+" das 7 lições originais registradas. As novas não alteram seus pontos":"Entre para sincronizar seu progresso";q("#member-progress").textContent=xp+" XP, "+Number(state.streak||0)+" dia(s) de sequência e "+Number((state.badges||[]).length)+" selo(s)"}
async function loadData(){if(!window.PuxaRotaAuth)return;q("#jobs-status").textContent="Consultando oportunidades no Supabase";q("#profiles-status").textContent="Consultando perfis autorizados";const data=await Promise.all([window.PuxaRotaAuth.listPublicOpportunities().catch(()=>[]),window.PuxaRotaAuth.listPublicProfiles().catch(()=>[])]);jobs=data[0]||[];profiles=data[1]||[];q("#job-count").textContent=jobs.length;q("#profile-count").textContent=profiles.length;if(jobs[0]){q("#best-job").textContent=jobs[0].title||jobs[0].company||"Nova oportunidade";q("#best-job-note").textContent=(jobs[0].company||"Empresa")+" · "+(jobs[0].origin||jobs[0].area||"consulte a região")}renderJobs();renderProfiles()}
async function loadProgress(){if(!auth||!window.PuxaRotaAuth){progress=null;renderProgress();return}const r=await window.PuxaRotaAuth.loadRouteProgress();progress=r&&r.ok?r.state||{}:{};renderProgress()}
function calculate(){const spend=Number(q("#spend").value),rate=Number(q("#rate").value);q("#spend-out").textContent=spend.toLocaleString("pt-BR");q("#rate-out").textContent=rate.toLocaleString("pt-BR");q("#result").textContent=money(spend*rate/100)}
function saveStudy(){localStorage.setItem(studyKey,JSON.stringify(studyState));renderLessons()}
function completeLesson(){if(!studyState.completed.includes(lessonIndex))studyState.completed.push(lessonIndex);saveStudy()}
function lessonMarkup(x){if(x.game)return '<div class="lesson-scene scene-'+(lessonIndex%5)+'"><img src="'+x.img+'" alt=""><div class="lesson-copy microgame"><span class="eyebrow">ATIVIDADE PRÁTICA</span><h2>'+esc(x.t)+'</h2><p>'+esc(x.body)+'</p><div class="game-board" id="game-board"><div class="game-road"></div><div class="game-wallet" id="game-wallet">Carteira NFC</div><button class="game-token" id="game-token"><span>&#8356;</span> USDT</button></div><p class="game-hint" id="game-hint">Arraste o saldo até a carteira ou toque no saldo e depois na carteira</p></div></div>';return '<div class="lesson-scene scene-'+(lessonIndex%5)+'"><img src="'+x.img+'" alt=""><div class="lesson-copy"><span class="eyebrow">'+(lessonIndex<7?"LIÇÃO PRESERVADA":"NOVA PRÁTICA")+'</span><h2>'+esc(x.t)+'</h2><p>'+esc(x.body)+'</p><div class="lesson-check"><b>'+esc(x.q)+'</b>'+x.o.map((o,i)=>'<button class="lesson-option" data-answer="'+i+'">'+esc(o)+'</button>').join("")+'</div></div></div>'}
function openLesson(index){lessonIndex=Math.max(0,Math.min(index,lessons.length-1));lessonReady=false;const x=lessons[lessonIndex],dialog=q("#lesson-dialog");q("#lesson-position").textContent="Li??o "+(lessonIndex+1)+" de "+lessons.length;q("#lesson-bar").style.width=((lessonIndex+1)/lessons.length*100)+"%";q("#lesson-stage").innerHTML=lessonMarkup(x);q("#lesson-back").disabled=lessonIndex===0;q("#lesson-next").disabled=true;q("#lesson-next").textContent=lessonIndex===lessons.length-1?"Concluir rota":"Continuar";dialog.showModal();if(x.game)setupGame()}
function setupGame(){const token=q("#game-token"),wallet=q("#game-wallet"),board=q("#game-board");let dragging=false,dx=0,dy=0,selected=false;const win=()=>{lessonReady=true;q("#lesson-next").disabled=false;q("#game-hint").textContent="Muito bem. Saldo preparado para o pagamento";q("#game-hint").className="game-hint game-success";token.style.left="auto";token.style.top="auto";token.style.right="11%";token.style.bottom="14%"};const hit=()=>{const a=token.getBoundingClientRect(),b=wallet.getBoundingClientRect();if(a.right>b.left&&a.left<b.right&&a.bottom>b.top&&a.top<b.bottom)win()};token.addEventListener("pointerdown",e=>{selected=true;dragging=true;token.setPointerCapture(e.pointerId);const r=token.getBoundingClientRect();dx=e.clientX-r.left;dy=e.clientY-r.top});token.addEventListener("pointermove",e=>{if(!dragging)return;const r=board.getBoundingClientRect();token.style.left=Math.max(0,Math.min(r.width-token.offsetWidth,e.clientX-r.left-dx))+"px";token.style.top=Math.max(0,Math.min(r.height-token.offsetHeight,e.clientY-r.top-dy))+"px";token.style.right="auto";token.style.bottom="auto"});token.addEventListener("pointerup",()=>{dragging=false;hit()});wallet.addEventListener("click",()=>{if(selected)win()})}
function nextIncomplete(){const remote=progress&&progress.routes&&progress.routes["beneficios-ripio"];const original=Math.min(Number(remote&&remote.step||0),6);const pending=lessons.findIndex((_,i)=>i>=7&&!studyState.completed.includes(i));return pending>=0&&(!auth||original>=6)?pending:original}
function isAdmin(){return Boolean(auth&&auth.account&&auth.account.account_type==="admin"&&auth.account.is_approved===true&&auth.user&&String(auth.user.email||"").toLowerCase()==="redeintegrativa@gmail.com")}
async function loadAdmin(){if(!isAdmin())return;const [p,o]=await Promise.all([window.PuxaRotaAuth.listAdminProfiles(),window.PuxaRotaAuth.listAdminOpportunities()]);if(!p.ok||!o.ok){q("#admin-status").textContent=p.reason||o.reason||"Não foi possível carregar a gestão";return}adminData={profiles:p.profiles||[],accounts:p.accounts||[],opportunities:o.opportunities||[]};q("#admin-status").textContent="Sessão administrativa ativa · "+auth.user.email;q("#admin-stats").innerHTML='<article><small>Perfis</small><strong>'+adminData.profiles.length+'</strong></article><article><small>Oportunidades</small><strong>'+adminData.opportunities.length+'</strong></article><article><small>Contas</small><strong>'+adminData.accounts.length+'</strong></article>';renderAdmin()}
function renderAdmin(){if(!adminData)return;const list=adminData[adminTab]||[];q("#admin-list").innerHTML=list.length?list.map(item=>{if(adminTab==="profiles")return '<article class="admin-item"><div><h3>'+esc(item.display_name||"Perfil sem nome")+'</h3><p>'+esc(item.profile_type||"perfil")+" · "+esc(item.region||"região não informada")+" · "+esc(item.status||"pendente")+'</p></div><div class="admin-actions"><button data-admin-action="profile-approve" data-id="'+item.id+'">Aprovar</button><button class="ghost" data-admin-action="profile-reject" data-id="'+item.id+'">Revisar</button></div></article>';if(adminTab==="opportunities")return '<article class="admin-item"><div><h3>'+esc(item.title||item.company||"Oportunidade")+'</h3><p>'+esc(item.company||"empresa")+" · "+esc(item.status||"pendente")+'</p></div><div class="admin-actions"><button data-admin-action="opportunity-approve" data-id="'+item.id+'">Aprovar</button><button class="ghost" data-admin-action="opportunity-reject" data-id="'+item.id+'">Rejeitar</button></div></article>';return '<article class="admin-item"><div><h3>'+esc(item.display_name||item.email_snapshot||"Conta")+'</h3><p>'+esc(item.account_type||"conta")+" · "+(item.is_approved?"aprovada":"aguardando")+'</p></div><div class="admin-actions"><button data-admin-action="account-toggle" data-id="'+item.user_id+'" data-approved="'+String(!item.is_approved)+'">'+(item.is_approved?"Suspender":"Aprovar")+'</button></div></article>'}).join(""):'<article class="admin-item"><h3>Nenhum item nesta lista</h3></article>'}
async function adminAction(button){const action=button.dataset.adminAction,id=button.dataset.id;if(!confirm("Confirmar esta alteração administrativa?"))return;button.disabled=true;let r;if(action==="profile-approve")r=await window.PuxaRotaAuth.reviewProfile(id,"approved","admin_release");if(action==="profile-reject")r=await window.PuxaRotaAuth.reviewProfile(id,"rejected");if(action==="opportunity-approve")r=await window.PuxaRotaAuth.reviewOpportunity(id,"approved");if(action==="opportunity-reject")r=await window.PuxaRotaAuth.reviewOpportunity(id,"rejected");if(action==="account-toggle")r=await window.PuxaRotaAuth.reviewAccount(id,button.dataset.approved==="true");if(!r||!r.ok)alert((r&&r.reason)||"Não foi possível concluir");await loadAdmin();await loadData()}
function setTheme(theme){document.documentElement.dataset.theme=theme;localStorage.setItem("puxarota-theme",theme);q("#theme-toggle").textContent=theme==="light"?"Tema escuro":"Tema claro"}
document.addEventListener("click",e=>{const nav=e.target.closest("[data-nav]"),goButton=e.target.closest("[data-go]"),detail=e.target.closest("[data-job-detail]"),lesson=e.target.closest("[data-lesson]"),answer=e.target.closest("[data-answer]"),tab=e.target.closest("[data-admin-tab]"),adminButton=e.target.closest("[data-admin-action]");if(nav)go(nav.dataset.nav);if(goButton)go(goButton.dataset.go);if(detail){const panel=q("#job-detail-"+detail.dataset.jobDetail),open=panel.hidden;panel.hidden=!open;detail.textContent=open?"Ocultar detalhes":"Ver detalhes";detail.setAttribute("aria-expanded",String(open))}if(lesson)openLesson(Number(lesson.dataset.lesson));if(answer){const x=lessons[lessonIndex],correct=Number(answer.dataset.answer)===x.a;qa(".lesson-option").forEach(b=>b.classList.remove("correct"));if(correct){answer.classList.add("correct");lessonReady=true;q("#lesson-next").disabled=false}else{answer.textContent="Tente outra resposta"}}if(tab){adminTab=tab.dataset.adminTab;qa("[data-admin-tab]").forEach(b=>b.classList.toggle("active",b===tab));renderAdmin()}if(adminButton)adminAction(adminButton)});
q("#job-search").addEventListener("input",renderJobs);q("#refresh-jobs").onclick=loadData;q("#spend").addEventListener("input",calculate);q("#rate").addEventListener("input",calculate);
const checklist=q("#checklist");qa("[data-partner]").forEach(b=>b.onclick=()=>{q("#checklist-title").textContent="Como garantir em "+b.dataset.partner;checklist.showModal()});q(".close").onclick=()=>checklist.close();q(".ok").onclick=()=>checklist.close();
q("#lesson-close").onclick=()=>q("#lesson-dialog").close();q("#lesson-back").onclick=()=>openLesson(lessonIndex-1);q("#lesson-next").onclick=()=>{if(!lessonReady)return;completeLesson();if(lessonIndex===lessons.length-1)q("#lesson-dialog").close();else openLesson(lessonIndex+1)};q("#start-next-lesson").onclick=()=>openLesson(nextIncomplete());
q("#logout").onclick=()=>window.PuxaRotaAuth&&window.PuxaRotaAuth.logout();q("#open-admin").onclick=async()=>{go("admin");await loadAdmin()};q("#theme-toggle").onclick=()=>setTheme(document.documentElement.dataset.theme==="light"?"dark":"light");
window.addEventListener("puxarota:auth",async e=>{auth=e.detail&&e.detail.session?e.detail:null;q("#member-study").hidden=!auth;q("#account-login").hidden=Boolean(auth);q("#open-admin").hidden=!isAdmin();if(auth){q("#member-name").textContent=(auth.profile&&auth.profile.display_name)||(auth.account&&auth.account.display_name)||(auth.user&&auth.user.email)||"Conta PuxaRota";q("#account-status").textContent="Sessão conectada ao Supabase"}await loadProgress();if(isAdmin())await loadAdmin()});
setTheme(localStorage.getItem("puxarota-theme")||"dark");renderLessons();calculate();renderProgress();go(location.hash.slice(1)||"hoje");window.addEventListener("DOMContentLoaded",()=>setTimeout(loadData,350));
})();
